name: Test

on:
  push:
    branches:
    - main
jobs: 
  workstation_docker_job:
    timeout-minutes: 35
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Start containers
      run: docker-compose -f "docker/workstation_computer/docker-compose-gui.yml" up -d --build
    - name: Stop containers
      run: docker-compose -f "docker/workstation_computer/docker-compose-gui.yml" down      
